[package]
name = "bss-oss-server"
version.workspace = true
edition.workspace = true
authors = ["Roberto de Souza <rabbittrix@hotmail.com>"]
license.workspace = true

[[bin]]
name = "bss-oss-rust"
path = "src/main.rs"

[dependencies]
tmf-apis-core = { path = "../tmf-apis/core" }
tmf620-catalog = { path = "../tmf-apis/tmf620_catalog" }
bss-oss-utils = { path = "../utils" }
actix-web.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
tokio.workspace = true
log.workspace = true
