{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bss-oss-rust.fullname" . }}
  labels:
    {{- include "bss-oss-rust.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "bss-oss-rust.selectorLabels" . | nindent 6 }}
{{- end }}

